---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - deploy

  environment:
    NODE_ENV: "{{ lookup('env','NODE_ENV') }}"
    PROD_PORT: "{{ lookup('env','PROD_PORT') }}"
    PROD_DB_HOST: "{{ lookup('env','PROD_DB_HOST') }}"
    PROD_DB_USER: "{{ lookup('env','PROD_DB_USER') }}"
    PROD_DB_PASSWORD: "{{ lookup('env','PROD_DB_PASSWORD') }}"
    PROD_DB_NAME: "{{ lookup('env','PROD_DB_NAME') }}"
    PROD_DB_DIALECT: "{{ lookup('env','PROD_DB_DIALECT') }}"
    