---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devopscapstone
  region: eu-west-2
  version: "1.21"

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 1
  ssh:
    allow: true
    publicKeyName: udacity

# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
